# use GHC 7.8.4
resolver: lts-2.0

packages:
- '.'

extra-deps:
- Spock-0.11.0.0
- Spock-core-0.11.0.0
- cryptonite-0.20
- memory-0.13
- hvect-0.3.1.0
- reroute-0.4.0.1
- Chart-cairo-1.8
- Chart-1.8
- html-entities-1.1.2
- plugins-1.5.5.0
- blaze-bootstrap-0.1.0.1

flags: {}

extra-package-dbs: []
